<?php
class Email
{    
	function email_sample($param)
	{
		$email_type = $param['type'];
		global $database;
		$param['type'] = 'group_admin';
		$additionalHeaders = "MIME-Version:1.0\r\n";
		$additionalHeaders .= "Content-Type: text/html\r\n"; 
		$additionalHeaders .= "Reply-To: no-reply<no-reply@quipmate.com>\r\n";
		$message = '';
		if($email_type == 'group_admin')
		{
			$friendid = $param['friendid'];
			$profileid = $param['profileid'];
			$groupid = $param['groupid'];
			$irow = $database->get_name($profileid);
			$grow = $database->get_group($groupid);
			$groupname = $grow['NAME'];
			$subject = '['.$groupname.'] ';
			$subject .= $irow['NAME'];   
			$subject .=' has made you admin of the group ';
			$subject .=$groupname;
			$brow = $database->bio_complete_select($friendid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_image($profileid);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;float:left;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="margin-left:80px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_name($profileid);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' has made you admin of the group ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$message .= ' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate.</a>';
			$message .= '</div>'; 
			$message .= ' <br /><br />To see the updates from the group ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$message .= ' Please visit this group at <a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<group-admin@quipmate.com>\r\n';
		}
		else if($email_type == 'event_cancel')
		{
			$eventname = $param['eventname'];
			$memberid = $param['memberid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$irow = $database->get_name($profileid);
			$subject= '['.$eventname.'] ';
			$subject .= $irow['NAME'];
			$subject .=' has canceled the event '.$eventname;
			$brow = $database->bio_complete_select($memberid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $memberid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' has canceled the event '.$eventname.' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= "<img style='border:none;' src='$file' width='40' height='40' />";
			$message .= '</a>';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id='.$actionby.'">Visit profile </a>to reply this action to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= '</body>';
			$message .= '</html>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<event-cancel@quipmate.com>\r\n';
		}
		else if($email_type == 'event_invite')
		{
			$profileid = $param['profileid'];
			$friendid = $param['friendid'];
			$eventid = $param['eventid'];
			$irow = $database->get_name($profileid);
			$grow = $database->event_select($eventid);
			$host =  $grow['host'];
			$eventname = $grow['name'];
			$subject= '('.$eventname.') ';
			$hrow = $database->get_name($host);
			$subject .= $irow['NAME'];
			$subject .=' has invited you to ';
			$subject .= $hrow['NAME'];
			$subject .='\'s event ';
			$subject .= $eventname;
			$brow = $database->bio_complete_select($friendid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_image($profileid);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_name($profileid);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' has invited you to the event ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/event.php?id=';
			$message .= $eventid; 
			$message .= '">'; 
			$message .= $eventname;
			$message .= '</a>';
			$message .= ' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To see the updates from the event ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/event.php?id=';
			$message .= $eventid; 
			$message .= '">'; 
			$message .= $eventname;
			$message .= '</a>';
			$message .= ' Please visit this event at <a style="text-decoration:none;" href="http://www.quipmate.com/">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/event.php?id=';
			$message .= $eventid; 
			$message .= '">'; 
			$message .= $eventname;
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<event-invite@quipmate.com>\r\n';
		} 
		else if($email_type == 'group_invite')
		{
			$profileid = $param['profileid'];
			$friendid = $param['friendid'];
			$groupid = $param['groupid'];
			$irow = $database->get_name($profileid);
			$subject = $irow['NAME'];
			$grow = $database->get_group($groupid);
			$groupname = $grow['NAME'];
			$subject .=' has added you to the group ';
			$subject .=$groupname;
			$brow = $database->bio_complete_select($friendid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_image($profileid);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_name($profileid);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' has added you into the group ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$message .= ' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To see the updates from the group ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$message .= ' Please visit this group at <a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id=';
			$message .= $groupid; 
			$message .= '">'; 
			$message .= $groupname;
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<group-invite@quipmate.com>\r\n';
			}  
		else if($email_type == 'event_post')
		{
			$eventid =  $param['eventid'];
			$memberid = $param['memberid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$post = $param['post'];
			$grow = $database->event_select($eventid);
			$eventname = $grow['name'];
			$subject = '['.$eventname.'] '.$post;
			$brow = $database->bio_complete_select($memberid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $memberid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' posted in  '.$eventname.' event at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$post.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/event.php?id='.$eventid.'">To reply </a>this post to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/event.php?id='.$eventid.'">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<event-post@quipmate.com>\r\n';
	    }
		else if($email_type == 'group_post')
		{
			$groupid =  $param['groupid'];
			$memberid = $param['memberid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$post = $param['post'];
			$grow = $database->get_group($profileid);
			$groupname = $grow['NAME'];
			$subject= '['.$groupname.'] '.$post;
			$brow = $database->bio_complete_select($memberid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $memberid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' posted in  '.$groupname.' group at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$post.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id='.$profileid.'">To reply </a>this post to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/group.php?id='.$profileid.'">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<group-post@quipmate.com>\r\n';
		}
		else if($email_type == 'birthday_bomb')
	    {
			$profileid =  $param['profileid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$actionid = $param['actionid'];
			$page = $param['page'];
			$subject= ' Birthday-bomed you. '.$page;
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL']; 
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' birthday bombed you at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$gift.'</span><br /><br />';
			$message .= 'To say thanx to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<birthday-wish@quipmate.com>\r\n';
		}
		else if($email_type == 'self_invite')
	    {
			$email = $param['email'];
			$identifier = $param['identifier'];
			$subject='Quipmate Registration Link';
			$message .= 'Hi ';
			$message .= $email.'</a>,<br /><br />';
			$message .='<div style="">';
			$message .= ' You recently initiated signup process at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.<br /><br />';
			$message .='</div>'; 
			$message .='</div>';
			$message .= 'Here is your registration link'."\n\n<br/>";
			$message .= '<a style="text-decoration:none;" href=';
			$message .= "http://www.quipmate.com/welcome.php?email=$email&identifier=$identifier";
			$message .= '>Register Now</a>';
			$message .= '<br /><br />You can do the following things at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a><br />';
			$message .='• Say Miss U to your friends in exciting new way<br />• Share Status,Link,Photo,Video and more with your friends<br />• Send Gift,Message and Birhday Bombs to your friends
			<br />• Define yourself by setting your Tagline<br />• Set your Mood and share it with your friends ';
			$additionalHeaders .= 'From:Quipmate<invitation@quipmate.com>\r\n';
		}
		else if($email_type == 'friend_invite')
	    {
			$email = $param['email'];
			$identifier = $param['identifier'];
			$myname = $param['myname'];
			$myphoto = $param['myphoto'];
			$myprofileid = $param['myprofileid'];	
			$subject='Invitation from '.$myname.' to join Quipmate';
			$message .= 'Hi ';
			$message .= $email.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $myprofileid; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $myphoto; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $myprofileid; 
			$message .= '">'; 
			$message .= $myname;
			$message .= '</a>';
			$message .= ' invited you to join <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.<br /><br />';
			$message .='</div>'; 
			$message .='</div>';
			$message .= 'Here is your invitation link'."\n\n<br/>";
			$message .= "http://www.quipmate.com/welcome.php?email=$email&identifier=$identifier";
			$message .= '<br /><br />You can do the following things at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a><br />';
			$message .='• Dedicate Song to your friends <br /> • Set a Song as your Status <br /> • Add your Love as Your Crush and Talk anonymously<br />• Say Miss U to your friends in exciting new way<br />• Share Status,Link,Photo,Video and more with your friends<br />• Send Gift,Message and Birhday Bombs to your friends
			<br />• Define yourself by setting your Tagline<br />• Set your Mood and share it with your friends<br />• Connect with your Alma Mater<br />• Connect with increasing number of colleges across India';
			$additionalHeaders .= 'From:'.$myname.'<invitation@quipmate.com>\r\n';
		}
		else if($email_type == 'password_recover')
	    {
			$email = $param['email'];
			$id = $param['uniqueid'];
			$subject='Recover Your Password';
			$message = "<a href = 'http://www.quipmate.com'><img src = 'http://www.quipmate.com/png/flogo.png' alt='Quipmate'></a>\n\n\n\r";
			$message .= 'Please click the following link to recover your password'."\n\n<br/>";
			$message .= "http://www.quipmate.com/welcome.php?click=recover_password&id=$id&email=$email";
			$additionalHeaders .= "From: Quipmate<recovery@quipmate.com>\r\n";
		}
		else if($email_type == 'friend_confirm')
	    {
			$profileid = $param['profileid'];
			$friendid = $param['friendid'];
			$subject='Friendship Confirmation';
			$brow = $database->bio_complete_select($friendid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_image($profileid);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$irow = $database->get_name($profileid);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' has confirmed you as friend at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To see the updates from ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit your home page at <a style="text-decoration:none;" href="http://www.quipmate.com/">';
			$message .= $name;
			$message .= '-Quipmate</a>';
			$message .= ' <br /><br />To learn about ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit the profile at <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<friend-confirm@quipmate.com>\r\n';
		}      
		else if($email_type == 'gift')
		{
			$profileid = $param['profileid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$gift = $param['gift'];
			$subject= $gift.' Send you a gift at Quipmate';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL']; 
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' send you a gift at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$gift.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=inbox">To give </a>a return gift to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<gift@quipmate.com>\r\n';
				
		}
		else if($email_type == 'email_confirm')
		{
			$email = $param['email'];
			$id = $param['id'];
			$name = $param['name'];
			$subject='Quipmate - Email Account Confirmation';
			$message .= '<div style="margin:10 40 20 40;">';
			$message .= 'Hi '.$name.',<br />';
			$message .= 'Please click '; 
			$message .= "<a href='http://www.quipmate.com/email_confirm.php?id=$id&email=$email'>here</a>";
			$message .= ' to confirm this email account provided by you to Quipmate.';
			$message .= '</div>';
			$message .= '<div style="margin:20 20 20 40;">';
			$message .= 'Additionally to visit Quipmate please click '.'<a style="text-decoration:none;" href="http://www.quipmate.com/">here</a>';
			$message .= '</div>';
			$message .= '<div style="margin:20 20 20 40;">';
			$message .= 'If you have forgotten your password please click ';
			$message .= "<a href='http://www.quipmate.com/forgot_password.php?id=$id&email=$email'>here</a>";
			$message .= ' to recover it.</div>';
			$additionalHeaders .= 'From:'. $irow['NAME'].'<email-confirmation@quipmate.com>\r\n';
		}
		else if($email_type == 'email_friend_request')
		{
			$email = $param['email'];
			$profileid = $param['profileid'];
			$name = $param['name'];
			$subject='Friend Requests';
			$message .= 'Hi '.$name.',<br />';
			$message .= 'The following people are interested in being your friend at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>. Please accept or deny them as your friend by visiting your profile at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate.</a>-<br /><br />'; 
			$result = $database->friend_invite_select($profileid);
			while($row =$result->fetch_array())
			{
			 $friendid = $row['FRIENDID'];
			 $message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			 $message .= $friendid; 
			 $message .= '">'; 
			 $irow = $database->get_image($friendid);
			 $file = $irow['CDN'].$irow['FILENAME'];
			 $file = $file;
			 $message .='<img style="border:none;" src="';
			 $message .= $file; 
			 $message .= '" width="80" height="80" />'; 
			 $message .= '</a>';
			 $message .='<div style="position:relative;top:10px;">';
			 $message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			 $message .= $friendid; 
			 $message .= '">'; 
			 $irow = $database->get_name($friendid);
			 $message .= $irow['NAME'];
			 $message .= '</a>';
			 $message .='</div>';
			 $message .='</div>';
			}
			$additionalHeaders .= 'From:'. $irow['NAME'].'<friend-request@quipmate.com>\r\n';
		} 
		else if($email_type == 'response')
		{
			$profileid = $param['profileid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$actiontype = $param['actiontype'];
			$subject = 'Excited at post';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			switch($actiontype)
			{ 
				case '11': $message .= ' says your status is exciting'; $subject= 'Your status is exciting'; break;
				case '12': $message .= ' says your profile update is exciting'; $subject= 'Your profile update is exciting'; break;
				case '15': $message .= ' says your photo is exciting'; $subject= 'Your photo is exciting'; break;
				case '17': $message .= ' says your friendhip is exciting'; $subject= 'Your friendhip is exciting'; break;
				case '511': $message .= ' says your missing by someone is exciting'; $subject= 'Your missing by someone is exciting'; break;
				case '811': $message .= ' says your tagline is exciting'; $subject= 'Your tagline is exciting'; break;
				case '1111': $message .= ' says crush at you by someone is exciting'; $subject= 'Crush at you by someone is exciting'; break;
				case '1113': $message .= ' says your crush match with someone is exciting'; $subject= 'Your crush match with someone is exciting'; break;
				case '1211': $message .= ' says your mood is exciting'; $subject= 'Your mood is exciting'; break;
				case '1411': $message .= ' says your gift is exciting'; $subject= 'Your gift is exciting'; break;
				case '1611': $message .= ' says your link is exciting'; $subject= 'Your link is exciting'; break;
				case '2011': $message .= ' says your status-song is exciting'; $subject = 'Your status-song is exciting'; break;
				case '2111': $message .= ' says your song-dedication is exciting'; $subject= 'Your song-dedication is exciting'; break;
				case '16': $message .= ' new-pinched you.'; $subject= $irow['NAME'].' new-pinched you'; break;
				default: $message .= ' says your post is exciting'; $subject= 'Your post is exciting'; break;
			}
			$message .= ' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a><br /><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">To reply </a>this response to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<response@quipmate.com>\r\n';
		}
		else if($email_type == 'college_connect_feature_display')
		{
			$profileid = $param['profileid'];
			$subject= 'An Initiative To Connect Colleges Across India';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a> is working at connecting people across all the colleges of India.<br />';
			$message .=' A new feature <a style="text-decoration:none;" href="http://www.quipmate.com/college_connect.php">College Connect</a> helps one send messages and and reach the emails of the people from these colleges.';
			$message .= 'You can reach these colleges by visiting <a style="text-decoration:none;"  href="http://www.quipmate.com/college_connect.php">College Connect</a> at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>';
			$additionalHeaders .= 'From:College Connect<college-connect@quipmate.com>\r\n';
		}
		else if($email_type == 'college_connect')
		{ 
			$profileid = $param['profileid'];
			$subject= 'An Initiative To Connect Colleges Across India';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a> is working at connecting people across all the colleges of India.<br />';
			$message .=' A new feature <a style="text-decoration:none;" href="http://www.quipmate.com/college_connect.php">College Connect</a> helps one send messages and and reach the emails of the people from these colleges.';
			$message .= 'You have not provided your college information. Please do so by visiting <a style="text-decoration:none;" href="http://www.quipmate.com/profileedit.php?t=edu">Edit Profile </a>at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>';
			$additionalHeaders .= 'From:College Connect<college-connect@quipmate.com>\r\n';
		}
		else if($email_type == 'comment')
		{
			$profileid = $param['profileid']; 
			$actionby = $param['actionby']; 
			$actionid = $param['actionid']; 
			$comment = $param['comment']; 
			$actiontype = $param['actiontype'];
			$subject= $comment;
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' commented at your ';
			switch($actiontype)
			{
				case '2': $message .= 'post'; break; 
				case '4': $message .= 'opinion'; break;
				case '23': $message .= 'special moment'; break;
				case '24': $message .= 'photo'; break;
				case '25': $message .= 'new profile photo'; break;
				case '26': $message .= 'friendship'; break;
				case '503': $message .= 'Missing by Someone'; break;
				case '802': $message .= 'tagline'; break;
				case '1103': $message .= 'Crush by someone'; break;
				case '1104': $message .= 'Crush Match with someone'; break;
				case '1202': $message .= 'mood'; break;
				case '1402': $message .= 'gift'; break;
				case '1602': $message .= 'link'; break;
				case '2002': $message .= 'status-song'; break;
				case '2102': $message .= 'dedicated song';
			}
			$message .= ' at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$comment.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">To reply </a>this comment to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<post-comment@quipmate.com>\r\n';
		}
		else if($email_type == 'message')
		{ 
			$profileid = $param['profileid'];
			$actionby = $param['actionby'];
			$mess = $param['message'];
			$subject= $mess;
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' sent you a message at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$mess.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=inbox">To reply </a>this message to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/?hl=inbox">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<message@quipmate.com>\r\n';
		}
		else if($email_type == 'missu_return')
		{ 
			$profileid = $param['profileid'];
			$actionby = $param['actionby']; 
			$actionid = $param['actionid']; 
			$subject = 'Miss back';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$subject='Miss U Return by '.$irow['NAME'];
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' Missed U back in response to your Miss U at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To respond to <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit the profile at ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<missu@quipmate.com>\r\n';
		}
		else if($email_type == 'missu')
		{		
			$profileid = $param['profileid'];
			$actionby = $param['actionby']; 
			$actionid = $param['actionid']; 
			$subject .= 'Miss U';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$subject='Miss U by '.$irow['NAME'];
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' is missing you at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To respond to <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit the profile at ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' and click <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= 'Miss Back';
			$message .= '</a>.';
			$message .= ' Otherwise ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' will keep missing you.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<missu@quipmate.com>\r\n';
		}
		else if($email_type == 'profile_post')
		{ 
			$profileid = $param['profileid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$post = $param['post'];
			$subject= $post;
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' posted in your diary at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$post.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">To reply </a>this post to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click <a style="text-decoration:none;" href="http://www.quipmate.com/?hl=diary">here</a>.';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<profile-post@quipmate.com>\r\n';
		}
		else if($email_type == 'friend_request')
		{		
			$profileid = $param['profileid'];
			$friendid = $param['friendid'];
			$subject .= 'Friend Request';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$irow = $database->get_image($friendid);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$irow = $database->get_name($friendid);
			$message .= $irow['NAME'];
			$subject='Friend Request by '.$irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' is interested in being your friend at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />Please accept or deny <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' as your friend by visiting your profile at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate.</a><br /><br />';
			$message .= ' <br />To learn about ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit the profile at <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $friendid; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<friend-request@quipmate.com>\r\n';
		}
		else if($email_type == 'friend_request_broadcast')
		{
			$profileid = $param['profileid'];
			$email = $param['email'];
			$name = $param['name'];
			$subject='Friend Requests';
			$message .= 'Hi '.$name.',<br />';
			$message .= 'The following people are interested in being your friend at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>. Please accept or deny them as your friend by visiting your profile at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate.</a>-<br /><br />'; 
			global $database;
			$result = $database->friend_invite_select($profileid);
			while($row =$result->fetch_array())
			{
				$friendid = $row['FRIENDID'];
				$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
				$message .= $friendid; 
				$message .= '">'; 
				$irow = $database->get_image($friendid);
				$file = $irow['CDN'].$irow['FILENAME'];
				$file = $file;
				$message .='<img style="border:none;" src="';
				$message .= $file; 
				$message .= '" width="80" height="80" />'; 
				$message .= '</a>';
				$message .='<div style="position:relative;top:10px;">';
				$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
				$message .= $friendid; 
				$message .= '">'; 
				$irow = $database->get_name($friendid);
				$message .= $irow['NAME'];
				$message .= '</a>';
				$message .='</div>';
				$message .='</div>';
			} 
			$additionalHeaders .= 'From:'.$irow['NAME'].'<friend-request@quipmate.com>\r\n';
		}      
		else if($email_type == 'sample_friend_request_email')
		{
			$email = $param['email']; 
			$profileid = $param['profileid'];
			$name = $param['name'];
			$subject='Friend Requests';
			$message .= 'Hi '.$name.',<br />';
			$message .= 'The following people are interested in being your friend at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>. Please accept or deny them as your friend by visiting your profile at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate.</a>-<br /><br />'; 
			global $database;
			$result = $database->friend_invite_select($profileid);
			while($row =$result->fetch_array())
			{
				$friendid = $row['FRIENDID'];
				$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
				$message .= $friendid; 
				$message .= '">'; 
				$irow = $database->get_image($friendid);
				$file = $irow['CDN'].$irow['FILENAME'];
				$file = $file;
				$message .='<img style="border:none;" src="';
				$message .= $file; 
				$message .= '" width="80" height="80" />'; 
				$message .= '</a>';
				$message .='<div style="position:relative;top:10px;">';
				$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
				$message .= $friendid; 
				$message .= '">'; 
				$irow = $database->get_name($friendid);
				$message .= $irow['NAME'];
				$message .= '</a>';
				$message .='</div>';
				$message .='</div>';
				$additionalHeaders .= 'From:'.$irow['NAME'].'<friend_request@quipmate.com>\r\n';
			}
			$additionalHeaders .= "From: Quipmate<friend-request@quipmate.com>\r\n";
		}
		else if ($email_type == 'praised')
		{
			$profileid = $param['profileid'];
			$actionby = $param['actionby']; 
			$actionid = $param['actionid']; 
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br /><br />';
			$message .='<div style=""><a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME'];
			$file = $file;
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="80" height="80" />'; 
			$message .= '</a>';
			$message .='<div style="position:relative;top:10px;">';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$subject='Praised by '.$irow['NAME'];
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .='</div>'; 
			$message .='</div>';
			$message .= ' has praised you at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>.';
			$message .= ' <br /><br />To respond to <a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please visit the profile at ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<missu@quipmate.com>\r\n';
		}
		else if ($email_type == 'direct_letter')
		{
			$profileid = $param['profileid'];
			$actionby = $param['actionby'];
			$actionid = $param['actionid'];
			$direct_letter = $param['direct_letter'];
			$subject = $direct_letter.' Sent you a direct letter at Quipmate';
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL']; 
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' sent you a direct letter at <a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate </a>.<br /><br />';
			// $irow = $database->get_image($actionby);
			$file = $irow['CDN'].$irow['FILENAME']; 
			$file = $file;
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$message .='<img style="border:none;" src="';
			$message .= $file; 
			$message .= '" width="40" height="40" />'; 
			$message .= '</a>';
			$message .= '<span style="margin-left:20px;">'.$gift.'</span><br /><br />';
			$message .= '<a style="text-decoration:none;" href="http://www.quipmate.com/?hl=inbox">To give </a>a return gift to ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' please click ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<direct-letter@quipmate.com>\r\n';
		}
		else if($email_type == 'Answered_Question')
		{
			$profileid = $param['profileid']; 
			$actionby = $param['actionby']; 
			//$actionid = $param['actionid']; 
			//$comment = $param['comment']; 
			//$actiontype = $param['actiontype'];
			//$subject= $comment;
			$brow = $database->bio_complete_select($profileid);
			$email = $brow['EMAIL'];
			$name = $brow['NAME'];
			$message .= 'Hi ';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $profileid; 
			$message .= '">'; 
			$message .= $name.'</a>,<br />';
			$message .='<a style="text-decoration:none;" href="http://www.quipmate.com/profile.php?id=';
			$message .= $actionby; 
			$message .= '">'; 
			$irow = $database->get_name($actionby);
			$message .= $irow['NAME'];
			$message .= '</a>';
			$message .= ' has answered your question ';
			$additionalHeaders .= 'From:'.$irow['NAME'].'<answers@quipmate.com>\r\n';
		}
		$mes = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';
		$mes .= '<html>';
		$mes .= '<head>';
		$mes .= '<title>';
		$mes .= $subject;
		$mes .= '</title>';
		$mes .= '</head>';
		$mes .= '<body>';
		$mes .= '<div style="margin:20px;padding:20px;background:#f4f4f4;text-align:left">';
		$mes .= '<div style="text-align:right;"><a href="http://www.quipmate.com/"><img style="border:none;" src="http://icon.qmcdn.net/logo.png" alt="Quipmate" /></a></div>';
		$mes .= $message;
		$mes .= '<div>';
		$mes .= 'Happy Quipping'.'<br />'.'Thank You'.'<br />'.'<a style="text-decoration:none;" href="http://www.quipmate.com/">Quipmate</a>';
		$mes .= '</div>';
		$mes .= '</div>';
		$mes .= '</body>';
		$mes .= '</html>';
		return mail($email, $subject, $mes, $additionalHeaders);
	}
}
?>